data(mtcars)
require('car')
boxplot(mpg~factor(am),data=mtcars, main="Car Milage Data",
    xlab="Manual or Auto Transmision", ylab="Miles Per Gallon") 
mdl1<-lm(mpg~factor(am),mtcars)
mdl2<-lm(mpg~factor(am)+wt,mtcars)
mdl9<-lm(mpg~factor(am)+wt+hp,mtcars)
mdl10<-lm(mpg~factor(am)+wt+hp+disp,mtcars)
mdl11<-lm(mpg~factor(am)+wt+hp+disp+cyl,mtcars)
mdl12<-lm(mpg~factor(am)+wt+hp+drat,mtcars)
mdl13<-lm(mpg~factor(am)+wt+hp+qsec,mtcars)
mdl14<-lm(mpg~factor(am)+wt+hp+factor(vs),mtcars)
mdl15<-lm(mpg~factor(am)+wt+hp+gear,mtcars)
mdl16<-lm(mpg~factor(am)+wt+hp+carb,mtcars)
mdl17<-lm(mpg~factor(am)+wt+hp+carb+gear,mtcars)

vif(mdl2)
vif(mdl9)
vif(mdl10)
vif(mdl11)
anova(mdl2,mdl9,mdl10,mdl11)
vif(mdl9)
vif(mdl12)
anova(mdl9,mdl12)
vif(mdl9)
vif(mdl13)
anova(mdl9,mdl13)
vif(mdl9)
vif(mdl14)
anova(mdl9,mdl14)
vif(mdl9)
vif(mdl15)
anova(mdl9,mdl15)
vif(mdl9)
vif(mdl16)
anova(mdl9,mdl16)
vif(mdl9)
vif(mdl17)
anova(mdl9,mdl15,mdl16,mdl17)

deviance(mdl2)
deviance(mdl9)





